version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/var/www/html
    depends_on:
      - redis
    env_file:
      - .env
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
