name: Laravel CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - uses: actions/checkout@v4

      # 2️⃣ Setup PHP with required extensions
      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: mbstring, bcmath, xml, curl, pdo, pdo_sqlite
          ini-values: post_max_size=256M, memory_limit=2G

      # 3️⃣ Update Composer
      - name: Update Composer
        working-directory: Backend
        run: composer self-update

      # 4️⃣ Copy .env
      - name: Copy .env
        working-directory: Backend
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      # 5️⃣ Install dependencies
      - name: Install Dependencies
        working-directory: Backend
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      # 6️⃣ Generate app key
      - name: Generate Key
        working-directory: Backend
        run: php artisan key:generate

      # 7️⃣ Set permissions
      - name: Directory Permissions
        working-directory: Backend
        run: chmod -R 777 storage bootstrap/cache

      # 8️⃣ Create SQLite database
      - name: Create SQLite Database
        working-directory: Backend
        run: |
          mkdir -p database
          touch database/database.sqlite

      # 9️⃣ Run migrations
      - name: Run Migrations
        working-directory: Backend
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: ${{ github.workspace }}/Backend/database/database.sqlite
        run: php artisan migrate --no-interaction --force
